[YouTubeMusicRevanced]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

[RedditRevanced]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[TiktokRevanced]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[TwitchRevanced]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"

[TwitterRevanced]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"

[YouTubeRevanced]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patcher-args = "-e 'Custom branding' -OcustomName=YouTube ReVanced"