[YouTube Music Revanced]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[Tiktok Revanced]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Twitch Revanced]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"

[Twitter Revanced]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"

[YouTube Revanced]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patcher-args = "-e 'Custom branding' -OcustomName=YouTube ReVanced"